---
  - name: Install gem bundler
    command: "chdir={{ project_root }} gem install bundler"
    environment:
      PATH: "{{ rvm_path }}"
      GEM_PATH: "{{ gem_path }}"

  - name: Bundle project gems
    command: "chdir={{ project_root }} bundle install"
    environment:
      PATH: "{{ rvm_path }}"
      GEM_PATH: "{{ gem_path }}"

  - name: Create databases
    command: "chdir={{ project_root }} rails db:setup"
    environment:
      PATH: "{{ rvm_path }}"
      GEM_PATH: "{{ gem_path }}"