---
- name: Remove Ruby Package
  become: true
  apt:
    name: ruby
    state: absent
    force: yes

- name: download gpg key for rvm
  shell: gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys D39DC0E3

- name: install rvm
  shell: \curl -L https://get.rvm.io | bash -s stable --autolibs=3 creates=~/.rvm

- name: install ruby
  shell: ~/.rvm/bin/rvm install --default {{ ruby_version }} creates=~/.rvm/rubies/{{ ruby_version }}
